[NWS-1750][NWS-1756] Add fourth block
nortan-projetos/nortan-projetos.github.io pull request #18
Opened 2022-08-08 19:21 UTC by leo-holanda

2022-08-10 22:00 UTC, WilamisAviz15 approved these changes

2022-08-12 22:37 UTC, augustoicaro requested changes
Alterar o espaçamento do bloco na versão mobile, para ficar similar ao bloco 3.

2022-08-12 23:14 UTC, leo-holanda commented
![Screenshot from 2022-08-12 20-14-33](https://user-images.githubusercontent.com/26936076/184455810-e615104a-c367-4314-b91b-e9d0d8409364.png)

2022-08-16 03:54 UTC, augustoicaro approved these changes
Só faz o rebase

2022-08-16 22:35 UTC, merged