[NWS-1750][NWS-1755]  Create block 3
nortan-projetos/nortan-projetos.github.io pull request #19
Opened 2022-08-08 21:27 UTC by WilamisAviz15

2022-08-08 21:27 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/183517790-b869a801-8d6a-4cea-aa42-33744de0f1e8.png)

2022-08-09 23:17 UTC, leo-holanda commented
@WilamisAviz15 quando puder manda um print como mobile por favor

2022-08-11 23:20 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/184258239-d37f4a1b-96ef-472a-b833-bb5ab3963a69.png)

2022-08-12 00:41 UTC, leo-holanda requested changes
Acho que faltou só a setinha @WilamisAviz15 
![Screenshot from 2022-08-11 21-37-56](https://user-images.githubusercontent.com/26936076/184264584-0b4e3bf8-d736-4a7e-8f92-0912a4ef50fe.png)
Esqueci de combinar contigo se entraria no meu PR ou no teu, mas o meu do bloco dois já foi mergeado. No meu PR do bloco 6 eu usei essa setinha caso tu queria dar uma olhada

2022-08-12 22:19 UTC, augustoicaro approved these changes
Só vê esse ponto da setinha que o Leo falou.

2022-08-12 22:42 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/184453647-1e7f2285-bd71-4a60-b0ec-da29b9063451.png)
![image](https://user-images.githubusercontent.com/58791888/184453654-c73fdae5-9b29-4105-af4e-fa177b65b278.png)

2022-08-12 22:43 UTC, augustoicaro approved these changes

2022-08-12 22:44 UTC, leo-holanda approved these changes

2022-08-16 03:53 UTC, merged