[NWS-1750][NWS-1753] Create first block
nortan-projetos/nortan-projetos.github.io pull request #20
Opened 2022-08-09 01:04 UTC by EduhFarias

Desktop:
![desktop](https://user-images.githubusercontent.com/30202709/183540398-44812e01-630a-4c70-8ff7-8c3a7e452719.png)

Mobile:
![mobile](https://user-images.githubusercontent.com/30202709/183540405-61975ccf-9e39-418c-a970-2d0c7858d127.png)

2022-08-11 00:29 UTC, EduhFarias commented
Adição do input para telefone:
![oie_PsdeqSjTthZS](https://user-images.githubusercontent.com/30202709/184045368-610d17c2-63b0-483a-a2be-c57c8c45dde5.png)

2022-08-11 23:15 UTC, Elygledson approved these changes
Hugo ainda não enviei a foto?

2022-08-12 22:13 UTC, augustoicaro requested changes
Aproveita também para fazer o rebase para o outorga-page

2022-08-12 22:13 UTC, augustoicaro commented on _includes/outorga-page/first_block
> +    </form>
Serão 2 form distintos, um para o email e outro para o telefone

2022-08-12 23:50 UTC, EduhFarias commented
![oie_CBhaVfnFEBNJ](https://user-images.githubusercontent.com/30202709/184457730-0a1e84f4-52a5-40a6-95cd-e202b24c7924.png)

2022-08-16 00:14 UTC, EduhFarias commented
![oie_m9DJgP2Tuf1j](https://user-images.githubusercontent.com/30202709/184757209-5c1b6948-f3c7-4c9b-bc12-24337850de3c.png)

2022-08-16 03:49 UTC, augustoicaro requested changes
Só faz essa alteração do scss para fecharmos esse bloco

2022-08-16 03:49 UTC, augustoicaro commented on _sass/minimal-mistakes.scss
> +.first_block {
Deixa no padrão de deixar as coisas do bloco num arquivo separado

2022-08-16 03:55 UTC, augustoicaro commented on _sass/minimal-mistakes.scss
> +.first_block {
E faz o rebase por favor

2022-08-16 23:09 UTC, merged