[NWS-1750][NWS-1759] Create seventh block
nortan-projetos/nortan-projetos.github.io pull request #24
Opened 2022-08-10 22:57 UTC by WilamisAviz15

2022-08-10 22:58 UTC, WilamisAviz15 commented
![image](https://user-images.githubusercontent.com/58791888/184037351-62c935c9-9e3c-4a20-9c6d-4f13ba13fa44.png)
![mobile](https://user-images.githubusercontent.com/58791888/184037371-dfb7ce9b-d3c2-420a-9549-72b0c62ce02a.png)

2022-08-16 23:17 UTC, augustoicaro requested changes
Para anter o padrão dos outros blocos bora fazer esse ponto que levantei

2022-08-16 23:17 UTC, augustoicaro commented on _sass/minimal-mistakes.scss
> +.seventh-block {
Separar o setimo bloco num arquivo isolado

2022-08-17 23:31 UTC, Elygledson commented on _sass/minimal-mistakes.scss
> +.seventh-block {
Eu tinha feito assim ai eu dei uma olhada para nos outros pulls para manter algo padronizado.

2022-08-18 00:54 UTC, WilamisAviz15 commented on _sass/minimal-mistakes.scss
> +.seventh-block {
feito

2022-08-19 22:58 UTC, augustoicaro approved these changes

2022-08-19 23:02 UTC, Elygledson approved these changes

2022-08-19 23:04 UTC, merged